spring:
  # MySQL 관련 설정
  application:
    name: backend
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 15MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/look4me?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    #    username: admin
    #    password: zzknu123!
    username: root
    password: dntjr3500
    hikari:
      max-lifetime: 170000

#  config:
#    additional-location: classpath:application-secret.yml
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    max-http-form-post-size: 15MB
# ---------- <h2 Database 관련> ----------
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  # H2 Setting Info (H2 Console? ???? ?? ???? ??)
#  application:
#    name: helpYoun
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:~/temp
#    username: youn
#    password: 1234
#    # 인터넷 보고 추가했음
#    # JPA 설정
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: create        # DB 초기화 전략 (none, create, create-drop, update, validate)
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#        format_sql: true      # 쿼리 로그 포맷 (정렬)
#        show_sql: true